version: "3.8"
services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spacedrop
    ports:
      - "0.0.0.0:5432:5432"
    command:
      - "postgres"
      - "-c"
      - "log_statement=all"
  
  redis: 
    image: redis:alpine
    restart: always
    ports: 
      - '0.0.0.0:6379:6379'